# OK=0, WARN=1, ERROR=2. STALE=3

# Diagnostics to evaluate
log_diagnostics:
  - node_name: "bento_box.bento_drive_node"
    # Higher priority overwrites lower priority in a latching manner.
    log_messages:
      - name: "can_transmission"
        keyword: "Can transmission error" #alt? WARNING: Cannot open CAN device interface: CAN2
        message: "CAN error, make sure your hardware is working! Check with 'ip a'"
        level: ERROR
        priority: 2
      - name: "motorcontroller_error"
        keyword: "Error synchronizing with device" #alt? ERROR initializing motor controller with ID
        message: "A Motorcontroller is cooked or missing."
        level: ERROR
        priority: 1
      - name: "disabled_robot"
        keyword: "Disabling robot"
        message: "Motors Disabled!"
        level: WARN
        priority: 0
      - name: "enabled_robot"
        keyword: "Enabling robot"
        message: "Operating normally."
        level: OK
        priority: 0

nodename_diagnostics:
  - node_name: "bento_box/cam1.camera_node_1"
    message: "Camera 1 crashed, make sure it is plugged in and for wobbly contacts! Check with 'cam -l' and 'lsusb'"
    level: ERROR
  - node_name: "bento_box/cam2.camera_node_2"
    message: "Camera 2 crashed, make sure it is plugged in and for wobbly contacts! Check with 'cam -l' and 'lsusb'"
    level: ERROR

