# OK=0, WARN=1, ERROR=2. STALE=3

# Diagnostics to evaluate
diagnostics:
  - name: "bento_drive"
    # Higher priority overwrites lower priority in a latching manner.
    log_messages:
      - name: "can_transmission"
        keyword: "Can transmission error" #alt? WARNING: Cannot open CAN device interface: CAN2
        message: "CAN error, make sure your hardware is working! Check with 'ip a'"
        level: ERROR
        priority: 2
      - name: "motorcontroller_error"
        keyword: "ERROR initializing motor controller with ID"
        message: "Motorcontroller is fucked."
        level: ERROR
        priority: 1
      - name: "disabled_robot"
        keyword: "Disabling robot"
        message: "Motors Disabled!"
        level: WARN
        priority: 0
      - name: "enabled_robot"
        keyword: "Enabling robot"
        message: "Operating normally."
        level: OK
        priority: 0

